spring:
  datasource:
    url: jdbc:mysql://localhost:3306/temp
    username: root
    password: Josh@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
